// config.js

const ACCRED_LIST = {
    "AFC COMPIEGNE": "https://www.instagram.com/999constantpl/",
    "COMPIEGNE": "https://www.instagram.com/999constantpl/",
    "FC VERSAILLES": "louis.desloge@fcversailles.com",
    "US CHANTILLY": "https://www.instagram.com/uschantilly/",
    "US ORLEANS": "https://orleansloiretfoot.com/contact/",
    "NANTERRE": "https://www.nanterre92.com/club/acces/accreditations-journalistes/",
    "CHARTRES": "communication@ccmbf.fr",
    "PARIS 92": "julia@paris92.fr",
    "C'CHARTRES MHB": "manon.bougard@ccmhb.fr",
    "US CRETEIL": "https://uschb.fr/infos-pratiques/presse/",
    "IVRY": "neiville.fon@hand-ivry.org",
    "FRANCAIS VOLANTS": "contact.hockey@francais-volants.org"
};

const CUSTOM_LOGOS = {
    "NEUILLY MARNE": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFBGU236FyfoBrHk_y1Xn5bxmTvrMsWQ7tpQ&s",
    "CROIX FIC": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE2xTi43iwGH1QVEjocItKEjCuRFhrm6_GiQ&s",
    "RACING CLUB FRANCE" : "https://upload.wikimedia.org/wikipedia/fr/f/f4/RacingCFFootball-logoann%C3%A9es2010.svg",
    "AMIENS" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwpW1SpvIkzL4CVjU1oEaCcFw2AsEoHgHC4Q&s",
    "BASTIA" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLJDN4RtJGnmnJGs8bPXKgliHhF6QLsDNl5g&s",
    "COMPIEGNE" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReN2j3PlYxw-Sl0jYVapIGctyYdNPNgj1Hqw&s",
    "SARCELLES" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhxAaLbimUIiTJXgBeVQbJ6FbiDQuYNO6hpg&s",
    "CREIL" : "https://upload.wikimedia.org/wikipedia/fr/a/ac/Logo_AFC_Creil.svg",
    "ST QUENTIN O." : "https://upload.wikimedia.org/wikipedia/fr/5/50/Logo_Olympique_Saint-Quentin_-_ancien.svg",
    "DRANCY" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2kgsMHgP_88HTqvHJ5UXYwqYxKjfd1v4gkw&s",
    "CHARTRES FOOTBALL" : "https://upload.wikimedia.org/wikipedia/fr/thumb/8/85/Logo_C%27Chartres_Football_2018.svg/960px-Logo_C%27Chartres_Football_2018.svg.png",
    "LE PAYS DU VALOIS US" : "https://uslpv.fr/wp-content/uploads/2025/01/Design-sans-titre-1.png",
    "CAEN" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/79/Logo_SM_Caen_2016.svg/1536px-Logo_SM_Caen_2016.svg.png", 
    "AJACCIO" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/73/Logo_Gaz%C3%A9lec_Football_Club_Ajaccio_2012.svg/1864px-Logo_Gaz%C3%A9lec_Football_Club_Ajaccio_2012.svg.png",
    "QUEVILLY" : "https://upload.wikimedia.org/wikipedia/fr/c/c3/Logo_US_Quevilly_Rouen_2018.svg",
    "PAYS DE CASSEL US" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuvfBBLimVU3xKVYrrKEMUwhh8dok-ZZETug&s",
    "F.C.BALAGNE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c1/Logo_FC_Balagne_-_2022.svg/1402px-Logo_FC_Balagne_-_2022.svg.png",
    "METZ FC" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuQDKhDfpfHfD_wFiddBwtl0a8fnDprxnJ8Q&s",
    "PARIS SAINT-GERMAIN" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcT7rPHMxsie6O_wgqoO1KekpR9tvIP72moA&s",
    "LOSC LILLE 21" : "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/Logo_LOSC_Lille_2018.svg/1200px-Logo_LOSC_Lille_2018.svg.png",
    "PARIS FC" : "https://upload.wikimedia.org/wikipedia/fr/archive/d/db/20190512200040%21Logo_Paris_FC_2011.svg",
    "OLYMPIQUE LYONNAIS" : "https://upload.wikimedia.org/wikipedia/fr/a/a5/Logo_Olympique_Lyonnais_-_2022.svg",
    "MANTOIS" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSElOjGquoPUf3VgmaDxRlFwoyQknGeNH5_pA&s",
    "DUNKERQUE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/72/Logo_USL_Dunkerque_2025.svg/langfr-250px-Logo_USL_Dunkerque_2025.svg.png",
    "VIMY" : "https://upload.wikimedia.org/wikipedia/en/e/e4/US_Vimy_logo.png",
    "REIMS" : "https://www.francebleu.fr/pikapi/images/536f2485-f907-459a-92de-1631b8e03f28/1200x680?webp=false",
    "SAINT MAUR" : "https://upload.wikimedia.org/wikipedia/fr/9/96/VGA_St-Maur_FF_Logo.png",
    "MOLSHEIM" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7VtYerlhjq0PH6PNQrtevVCC5GfB6j-1bgw&s",
    "LORIENT" : "https://upload.wikimedia.org/wikipedia/fr/1/1d/Logo_FC_Lorient_Bretagne-Sud.svg",
    "ORLEANS" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtibTWqBQrmkrVUj49ANE1B64BzY9l0fvO1g&s",
    "VENDEE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/0/01/Logo_VFCLRSY.png/960px-Logo_VFCLRSY.png",
    "BREQUIGNY" : "https://tournois.fcgm.fr/wp-content/uploads/2014/10/Logo_CPB_Brequigny-200x200.png",
    "CHARNAY" : "https://www.proballers.com/api/getTeamLogo?id=13378&width=400",
    "EVREUX" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKx5oPX1Oeudd2zRPF8k2OCurpPkfEftCWfQ&s",
    "POITIERS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/d/db/Logo_Poitiers_Basket_86_-_2018.svg/1200px-Logo_Poitiers_Basket_86_-_2018.svg.png",
    "SAINT QUENTIN BASKET": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvFdMEPWokVacrlcRJpIk0-k50z9Q6708Gng&s",
    "LE PORTEL": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/da/Logo_ESSM_Le_Portel_C%C3%B4te_d%27Opale_-_2015.svg/960px-Logo_ESSM_Le_Portel_C%C3%B4te_d%27Opale_-_2015.svg.png",
    "POLE FRANCE": "https://upload.wikimedia.org/wikipedia/fr/1/13/Logo_P%C3%B4le_France_BB.png",
    "STADE FRANCAIS BASKET": "https://upload.wikimedia.org/wikipedia/commons/9/96/Logo_Stade_Fran%C3%A7ais_Basket_Fond_transparent_959x959.png",
    "LAMBOISIERES": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-3F3umKIfAKLRhrU4Prrh_3u2Nobiw0WIfA&s",
    "STADE ROCHELAIS": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/33/Logo_Stade_Rochelais_Basket_-_2018.svg/1200px-Logo_Stade_Rochelais_Basket_-_2018.svg.png",
    "NANTERRE": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqT_T2u__c_s5iOBMS5_zkR1ecN2ZETZh4Gg&s",
    "BOURG BASKET": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Logo_JL_Bourg_Basket_-_2017.svg/1050px-Logo_JL_Bourg_Basket_-_2017.svg.png",
    "LE MANS SCM": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlT1qbHTJoJSNNUoc2Qc58ig88EWB80OZN1A&s",
    "PARIS BASKETBALL": "https://upload.wikimedia.org/wikipedia/fr/archive/4/41/20240917070337%21Logo_Paris_Basketball_-_2024.svg",
    "BASKET CLUB FRANCONVILLE": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYAN5yONLzjTF2unHxzCu9TuzmXafFuAw0Uw&s",
    "COTE D'OPALE BASKET CALAIS": "https://upload.wikimedia.org/wikipedia/fr/f/f5/COB_Calais_2014.png",
    "ASA SCEAUX": "https://dagoba-boutiques-01.s3.amazonaws.com/vendor0939/images/0001210962/sceaux_logo_180--0-0--813f7d22-d923-4e57-9ba3-3cccdddf389f.png",
    "LA TRONCHE MEYLAN": "https://media.scorenco.com/media/image/club-logo-1708424981.25292.png",
    "TOULOUSE": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Logo-tmb-Toulouse-basket.png",
    "AS MONACO": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/ff/Logo_AS_Monaco_Basket.svg/1524px-Logo_AS_Monaco_Basket.svg.png",
    "LE MANS SARTHE BASKET": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Le_Mans_Sarthe_Basket_logo_nouveau.png/250px-Le_Mans_Sarthe_Basket_logo_nouveau.png",
    "ASVEL BASKET (SAS)": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9_mOGuhwJ9b_mt8vaB_TZ2Uzmxn-it-VTOQ&s",
    "SEM ELAN CHALON": "https://upload.wikimedia.org/wikipedia/fr/c/c3/Logo_Elan_Chalon_2018.svg",
    "LIMOGES CSP": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Logo_CSP_VECTO.svg/langfr-250px-Logo_CSP_VECTO.svg.png",
    "SAINT-AMAND HAINAUT": "https://upload.wikimedia.org/wikipedia/fr/d/d1/Logo_Saint-Amand_Hainaut_Basket_%282020%29.png",
    "SLUC NANCY": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/SLUC_Nancy_%28logo%29.svg/2048px-SLUC_Nancy_%28logo%29.svg.png",
    "JDA DIJON": "https://upload.wikimedia.org/wikipedia/commons/0/01/JDA_Dijon_Basket.png",
    "LANDERNEAU": "https://upload.wikimedia.org/wikipedia/fr/1/19/Logo_lbb_2018.png",
    "CHARLEVILLE" : "https://upload.wikimedia.org/wikipedia/fr/8/8b/Etoile_Charleville_2015.png",
    "CHAMPAGNE" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpe1OInhTKIdS6Ss_e3UJKLlWyn1Mdz2Uz0w&s",
    "ESCAUDAIN" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2kTm_by0tvVVnliDU99BFlnYnaj2CfvWliA&s",
    "VICHY" : "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Logo_JA_Vichy_Basket_-_2023.svg/1200px-Logo_JA_Vichy_Basket_-_2023.svg.png",
    "CHAMBRAY": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkjWDdgQ4yCp3hVsJXZLPLdvAExin6cwnydg&s",
    "BESANCON": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/fc/ESBF_2019.png/1200px-ESBF_2019.png",
    "SAINT-MAUR": "https://upload.wikimedia.org/wikipedia/fr/e/e7/Stella_Saint-Maur_Handball_Logo.png",
    "TOULON": "https://upload.wikimedia.org/wikipedia/fr/b/b1/Logo_du_Toulon_M%C3%A9tropole_Var_Handball.png",
    "ST AMAND": "https://upload.wikimedia.org/wikipedia/fr/9/90/Saint-Amand_Handball_Logo.png",
    "STRASBOURG ACHENHEIM": "https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img/https://www.placedeshalles.com/wp-content/uploads/2024/07/SATH.jpg",
    "PARIS 92": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/60/Paris_92.svg/1200px-Paris_92.svg.png",
    "SAMBRE AVESNOIS": "https://www.sportstrategies.com/wp-content/uploads/2022/05/1652438143745.png",
    "METZ HANDBALL": "https://upload.wikimedia.org/wikipedia/fr/e/e8/Metz_Handball_logo_2014.png",
    "CRETEIL": "https://i0.wp.com/uschb.fr/wp-content/uploads/2023/07/USCHB_Logo_2025.png?fit=1200%2C1200&ssl=1",
    "SARAN": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHYua2tIwoXgjUZhL9sSEsQxbl9A3VTBpjkA&s",
    "IVRY": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/6d/US_Ivry_Handball_logo_2016.svg/960px-US_Ivry_Handball_logo_2016.svg.png",
    "PONTAULT-COMBAULT": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmyrTbWBUhCNVs3CDOoeE-OVOzNv6LeIXcvA&s",
    "CERCLE SPORTIF VESULIEN": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_b52vv79c5gat4zRO42onxe1PaDkpGls4MA&s",
    "ELITE VAL-D'OISE": "https://upload.wikimedia.org/wikipedia/fr/0/01/LogoEVO.webp",
    "CERNAY/WATTWILLER": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQImlgZEwp2QmR8nTrGuIg_i6esrrtILVC5FQ&s",
    "NANTES HBC": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b9/HBC_Nantes_2011_logo.svg/1149px-HBC_Nantes_2011_logo.svg.png",
    "C'CHARTRES": "https://pro.ccmhb.fr/public/images/logo.png",
    "CHARTRES" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTu5M-6XaRLqvmUiVKhJQ8hlucDSBRmrsldg&s",
    "SELESTAT ALSACE": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a9/S%C3%A9lestat_Alsace_handball_2017.svg/1158px-S%C3%A9lestat_Alsace_handball_2017.svg.png",
    "TREMBLAY": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZm1mKnlqMNbOOV5XzBzjvigrYyzjfI-vv1w&s",
    "MASSY": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/40/Massy_Essonne_Handball_logo.png/250px-Massy_Essonne_Handball_logo.png",
    "ATHLETIC CLUB BOULOGNE": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a8/Athletic_Club_de_Boulogne-Billancourt_logo.svg/1200px-Athletic_Club_de_Boulogne-Billancourt_logo.svg.png",
    "COURNON D'AUVERGNE": "https://lnh.fr/medias/sports_teams/cournon-d-auvergne__logo__2023-2024.png",
    "OGC NICE COTE D'AZUR": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/91/Logo_OGC_Nice_Handball.svg/1200px-Logo_OGC_Nice_Handball.svg.png",
    "DUNKERQUE GRAND LITTORAL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR47Lmq47kquHMkgKxQFuz7TYm8ksaSYcqZJA&s",
    "ANGERS": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhP-ZhT1JmqvjV63lqoJrIZF4p4Yf9ZOSdfQ&s",
    "PAU BILLERE": "https://upload.wikimedia.org/wikipedia/fr/9/98/Logo_du_Pau_Bill%C3%A8re_Handball_2024.png",
    "VALENCE" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJkjuY-OlZH7sim_s4iZ1X03jkmzvGgvoqw&s",
    "SARREBOURG MOSELLE SUD" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8SZ3f_XLde2J_RXSDtsN-ZX_TILvFA6X39Q&s"
};

const STADIUM_COORDS = {
    "AAS SARCELLES": { lat: 48.995, lon: 2.380 },
    "AAS SARCELLES 21": { lat: 48.995, lon: 2.380 },
    "AFC COMPIEGNE": { lat: 49.406, lon: 2.812 },
    "AFC CREIL 21": { lat: 49.256, lon: 2.477 },
    "ALM EVREUX BASKET": { lat: 49.020, lon: 1.144 },
    "AMIENS SCF 2": { lat: 49.894, lon: 2.264 },
    "ASA SCEAUX": { lat: 48.777, lon: 2.296 },
    "BASKET CLUB FRANCONVILLE (BCF) - 1": { lat: 48.991, lon: 2.223 },
    "C CHARTRES FOOTBALL 23": { lat: 48.452, lon: 1.480 },
    "CHARTRES": { lat: 48.441, lon: 1.503 },
    "CS BRETIGNY FOOTBALL": { lat: 48.608, lon: 2.308 },
    "CS MAINVILLIERS": { lat: 48.441, lon: 1.464 },
    "JEANNE D'ARC DRANCY": { lat: 48.926, lon: 2.443 },
    "LE MANS SARTHE BASKET": { lat: 47.954, lon: 0.232 },
    "LE PAYS DU VALOIS US": { lat: 49.141, lon: 3.012 },
    "LILLE LOSC 2": { lat: 50.574, lon: 3.208 },
    "MANTOIS 78 FC": { lat: 48.979, lon: 1.706 },
    "MONTROUGE FC 92": { lat: 48.814, lon: 2.316 },
    "NANTERRE 92": { lat: 48.895, lon: 2.217 },
    "NEUILLY MARNE SFC": { lat: 48.882, lon: 2.535 },
    "PARIS BASKETBALL ASSOCIATION": { lat: 48.899, lon: 2.361 },
    "PARIS FC": { lat: 48.819, lon: 2.348 },
    "PARIS FC 21": { lat: 48.730, lon: 2.404 },
    "PARIS SAINT-GERMAIN": { lat: 48.841, lon: 2.253 },
    "PAYS DE CASSEL US": { lat: 50.716, lon: 2.538 },
    "POLE FRANCE": { lat: 48.835, lon: 2.454 },
    "QUEVILLY RM": { lat: 49.408, lon: 1.074 },
    "RACING CLUB FRANCE": { lat: 48.929, lon: 2.249 },
    "SAINT DENIS RC": { lat: 48.934, lon: 2.349 },
    "SASP - SAINT QUENTIN BASKET BALL": { lat: 49.849, lon: 3.280 },
    "ST QUENTIN O.": { lat: 49.858, lon: 3.275 },
    "STADE DE REIMS 2": { lat: 49.293, lon: 4.053 },
    "STADE FRANCAIS BASKET": { lat: 48.844, lon: 2.254 },
    "US ORLEANS LOIRET": { lat: 47.839, lon: 1.932 },
    "VERSAILLES 78 FC": { lat: 48.805, lon: 2.138 },
    "VGA SAINT MAUR": { lat: 48.806, lon: 2.493 },
    "VIMY US": { lat: 50.375, lon: 2.808 },
    "STELLA": { lat: 48.804, lon: 2.483 }, 
    "CHAMBRAY": { lat: 47.339, lon: 0.708 },
    "PARIS 92": { lat: 48.825, lon: 2.274 }, 
    "CHARTRES": { lat: 48.434, lon: 1.488 }, 
    "PSG": { lat: 48.836, lon: 2.253 }, 
    "ELITE VAL-D'OISE": { lat: 48.990, lon: 2.221 }, 
    "TREMBLAY": { lat: 48.948, lon: 2.569 }, 
    "IVRY US": { lat: 48.812, lon: 2.392 }, 
    "CRETEIL": { lat: 48.776, lon: 2.450 }, 
    "PONTAULT-COMBAULT": { lat: 48.796, lon: 2.611 }, 
    "MASSY ESSONNE": { lat: 48.730, lon: 2.275 } 
};